# Generated by Django 5.1.1 on 2024-09-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_department_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='companies.department'),
        ),
    ]
